# This is a basic workflow to help you get started with Actions

name: Test

on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
    - run: |
        gem install rubocop:0.69
        gem install rubocop-performance:1.3 --ignore-dependencies
        rubocop
    
