name: Pronto

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: adwerx/pronto-ruby@v2.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
